name:                avito
version:             0.1.0.0
github:              "nlv/avito"
license:             BSD3
author:              "Leon Nikitin"
maintainer:          "nlvomsk@gmail.com"
copyright:           "Leon Nikitin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nlv/avito#readme>

dependencies:
- base >= 4.7 && < 5
- hxt
- cassava
- bytestring
- vector
- split
- MissingH
- pandoc
- text
- containers
- data-default
- curl
- download-curl
- modern-uri
- optparse-applicative

library:
  source-dirs: src

executables:
  avito-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - avito

tests:
  avito-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - avito
